# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [2]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [ ]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['bottom' '2' 'top' '2' 'top' 'top' 'top' 'top' 'top' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [ ]:
import numpy as np
print(np.random.choice(10))

Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [ ]:
import numpy as np
print(np.random.choice(10, size=(4, 6)))

### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [4]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[0 2 0 3 1 4 0 3 1 2]


Згенеруйте одну випадкову цифру.

In [ ]:
# Місце для Вашого коду
print(np.random.randint(10))

Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [ ]:
# Місце для Вашого коду
print(np.random.randint(low = 10, high = 100, size=(4, 5)))

### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [ ]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [5]:
print(np.random.sample(size=(3,4)))

[[0.53274123 0.14190965 0.57338245 0.00227237]
 [0.6465066  0.49739318 0.59189703 0.84761254]
 [0.55511169 0.27834583 0.08197491 0.1472456 ]]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [7]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[5 4 1 3 2 8 9 6 7 0]


Перетасуйте матрицю $M$.

In [10]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# Приклад

np.random.shuffle(M)
print(M)

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [11]:
print(np.random.randint(10))

4


In [ ]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [13]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['T' 'H' 'T' 'T' 'H' 'H' 'H' 'H' 'H' 'H']


In [14]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

7 heads and 3 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [5]:
# Місце для Вашого коду

tosses = np.random.choice(["H","T"], size=100)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

51 heads and 49 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [4]:
# Приклад

tosses = np.random.randint(2, size=100)
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

47 heads and 53 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [3]:
# Приклад

tosses = np.round(np.random.sample(100))
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

42 heads and 58 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [ ]:
# Приклад

params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for n in params:
    tosses = np.random.randint(2, size=n)
    heads_prob = sum(tosses == 1) / n
    tails_prob = sum(tosses == 0) / n
    print('n = {}  :  P(head) = {},  P(tail) = {}'.format(n, heads_prob, tails_prob))

n = 10  :  P(head) = 0.5,  P(tail) = 0.5
n = 50  :  P(head) = 0.46,  P(tail) = 0.54
n = 100  :  P(head) = 0.53,  P(tail) = 0.47
n = 250  :  P(head) = 0.456,  P(tail) = 0.544
n = 500  :  P(head) = 0.476,  P(tail) = 0.524
n = 1000  :  P(head) = 0.502,  P(tail) = 0.498
n = 2500  :  P(head) = 0.5004,  P(tail) = 0.4996
n = 5000  :  P(head) = 0.5026,  P(tail) = 0.4974
n = 10000  :  P(head) = 0.4983,  P(tail) = 0.5017


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [2]:
# Місце для Вашого коду
def find(arr, target):
  counter = 0
  for el in arr:
    if el == target:
      counter +=1
  return counter
t = np.random.randint(6, size=60)
print(t)
print(f'1 = {find(t, 0)} times, 2 = {find(t, 1)} times, 3 = {find(t, 2)} times')

[0 4 3 2 0 4 0 5 4 3 1 0 4 4 3 1 0 0 2 2 4 2 5 2 5 4 1 1 3 1 4 5 3 3 1 3 2
 1 4 0 1 5 2 3 5 3 0 4 3 1 4 1 5 1 1 1 1 2 2 2]
1 = 8 times, 2 = 14 times, 3 = 10 times


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [1]:
import numpy as np

params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for n in params:
    rolls = np.random.randint(1, 7, size=n)  # Кидаємо кубик n разів (значення від 1 до 6)
    probabilities = {i: np.sum(rolls == i) / n for i in range(1, 7)}  # Розрахунок емпіричних ймовірностей
    print(f"n = {n}  :  " + "  ".join([f"P({face}) = {prob:.4f}" for face, prob in probabilities.items()]))


n = 10  :  P(1) = 0.3000  P(2) = 0.1000  P(3) = 0.4000  P(4) = 0.1000  P(5) = 0.0000  P(6) = 0.1000
n = 50  :  P(1) = 0.2000  P(2) = 0.1400  P(3) = 0.1400  P(4) = 0.2000  P(5) = 0.2000  P(6) = 0.1200
n = 100  :  P(1) = 0.1500  P(2) = 0.2100  P(3) = 0.1800  P(4) = 0.1000  P(5) = 0.1900  P(6) = 0.1700
n = 250  :  P(1) = 0.1360  P(2) = 0.1960  P(3) = 0.1640  P(4) = 0.1720  P(5) = 0.1560  P(6) = 0.1760
n = 500  :  P(1) = 0.1480  P(2) = 0.1780  P(3) = 0.1780  P(4) = 0.1620  P(5) = 0.1620  P(6) = 0.1720
n = 1000  :  P(1) = 0.1630  P(2) = 0.2030  P(3) = 0.1690  P(4) = 0.1670  P(5) = 0.1380  P(6) = 0.1600
n = 2500  :  P(1) = 0.1604  P(2) = 0.1700  P(3) = 0.1664  P(4) = 0.1596  P(5) = 0.1752  P(6) = 0.1684
n = 5000  :  P(1) = 0.1656  P(2) = 0.1804  P(3) = 0.1622  P(4) = 0.1576  P(5) = 0.1746  P(6) = 0.1596
n = 10000  :  P(1) = 0.1670  P(2) = 0.1640  P(3) = 0.1661  P(4) = 0.1638  P(5) = 0.1669  P(6) = 0.1722


## 5 Колода карт
### 5.1 Реалізація

In [ ]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('2', '♡'), ('2', '♣'), ('2', '♠'), ('2', '♢'), ('9', '♡'), ('9', '♣'), ('9', '♠'), ('9', '♢'), ('10', '♡'), ('10', '♣'), ('10', '♠'), ('10', '♢'), ('Q', '♡'), ('Q', '♣'), ('Q', '♠'), ('Q', '♢'), ('7', '♡'), ('7', '♣'), ('7', '♠'), ('7', '♢'), ('8', '♡'), ('8', '♣'), ('8', '♠'), ('8', '♢'), ('K', '♡'), ('K', '♣'), ('K', '♠'), ('K', '♢'), ('6', '♡'), ('6', '♣'), ('6', '♠'), ('6', '♢'), ('5', '♡'), ('5', '♣'), ('5', '♠'), ('5', '♢'), ('1', '♡'), ('1', '♣'), ('1', '♠'), ('1', '♢'), ('J', '♡'), ('J', '♣'), ('J', '♠'), ('J', '♢'), ('4', '♡'), ('4', '♣'), ('4', '♠'), ('4', '♢'), ('3', '♡'), ('3', '♣'), ('3', '♠'), ('3', '♢')]


In [ ]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

2♡, 2♣, 2♠, 2♢, 9♡, 9♣, 9♠, 9♢, 10♡, 10♣, 10♠, 10♢, Q♡, Q♣, Q♠, Q♢, 7♡, 7♣, 7♠, 7♢, 8♡, 8♣, 8♠, 8♢, K♡, K♣, K♠, K♢, 6♡, 6♣, 6♠, 6♢, 5♡, 5♣, 5♠, 5♢, 1♡, 1♣, 1♠, 1♢, J♡, J♣, J♠, J♢, 4♡, 4♣, 4♠, 4♢, 3♡, 3♣, 3♠, 3♢


In [ ]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♡2, ♡9, ♡10, ♡Q, ♡7, ♡8, ♡K, ♡6, ♡5, ♡1, ♡J, ♡4, ♡3
♣2, ♣9, ♣10, ♣Q, ♣7, ♣8, ♣K, ♣6, ♣5, ♣1, ♣J, ♣4, ♣3
♠2, ♠9, ♠10, ♠Q, ♠7, ♠8, ♠K, ♠6, ♠5, ♠1, ♠J, ♠4, ♠3
♢2, ♢9, ♢10, ♢Q, ♢7, ♢8, ♢K, ♢6, ♢5, ♢1, ♢J, ♢4, ♢3


In [ ]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('K', '♠'), ('4', '♡'), ('7', '♢'), ('2', '♠'), ('6', '♣'), ('3', '♡'), ('7', '♠'), ('J', '♠'), ('J', '♣'), ('1', '♡'), ('4', '♢'), ('Q', '♣'), ('6', '♢'), ('K', '♡'), ('10', '♡'), ('2', '♡'), ('K', '♢'), ('8', '♠'), ('5', '♣'), ('9', '♡'), ('10', '♢'), ('10', '♠'), ('4', '♠'), ('J', '♡'), ('8', '♢'), ('6', '♠'), ('5', '♡'), ('9', '♣'), ('J', '♢'), ('6', '♡'), ('3', '♢'), ('9', '♢'), ('Q', '♢'), ('3', '♠'), ('4', '♣'), ('10', '♣'), ('9', '♠'), ('2', '♢'), ('K', '♣'), ('8', '♡'), ('1', '♢'), ('8', '♣'), ('3', '♣'), ('7', '♡'), ('5', '♠'), ('Q', '♠'), ('7', '♣'), ('1', '♣'), ('5', '♢'), ('Q', '♡'), ('1', '♠'), ('2', '♣')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [8]:
import numpy as np

ranks = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
suits = ['♠', '♣', '♦', '♥']

deck = [rank + suit for suit in suits for rank in ranks]

even_ranks = {'2', '4', '6', '8', '10'}

params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for n in params:
    chosen_cards = np.random.choice(deck, size=n, replace=True) 
    even_count = sum(1 for card in chosen_cards if card[:-1] in even_ranks) 
    even_prob = even_count / n
    print(f"n = {n}  :  P(is_even) = {even_prob:.4f}")


n = 10  :  P(парне число) = 0.5000
n = 50  :  P(парне число) = 0.3800
n = 100  :  P(парне число) = 0.3600
n = 250  :  P(парне число) = 0.3880
n = 500  :  P(парне число) = 0.3960
n = 1000  :  P(парне число) = 0.4010
n = 2500  :  P(парне число) = 0.3972
n = 5000  :  P(парне число) = 0.3860
n = 10000  :  P(парне число) = 0.3810


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [7]:
import random

suits = ['♠', '♣', '♦', '♥']
ranks = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']

deck = [rank + suit for suit in suits for rank in ranks]

random.shuffle(deck)

players = {f'Гравець {i+1}': [] for i in range(4)}

random.shuffle(suits)
player_suits = {f'Гравець {i+1}': suits[i] for i in range(4)}

for player, suit in player_suits.items():
    players[player].extend([card for card in deck if suit in card][:4])
    deck = [card for card in deck if card not in players[player]]  # Видаляємо роздані карти

    other_suits = [s for s in suits if s != suit]
    for other_suit in other_suits:
        players[player].extend([card for card in deck if other_suit in card][:3])
        deck = [card for card in deck if card not in players[player]]  # Видаляємо роздані карти

for player, cards in players.items():
    print(f"{player}: {', '.join(cards)}")


Гравець 1: 9♦, 5♦, J♦, A♦, A♠, J♠, K♠, 7♣, 4♣, 3♣, 7♥, J♥, Q♥
Гравець 2: 7♠, 4♠, 6♠, 9♠, 2♦, 10♦, 8♦, 8♣, J♣, 5♣, 6♥, 8♥, A♥
Гравець 3: 9♣, Q♣, 6♣, 10♣, 6♦, 7♦, Q♦, 10♠, 8♠, 2♠, 9♥, K♥, 4♥
Гравець 4: 2♥, 5♥, 3♥, 10♥, 3♦, 4♦, K♦, 3♠, Q♠, 5♠, K♣, 2♣, A♣
